version: 2.1

orbs:
  node: circleci/node@5.0.3

jobs:
  build:
    executor: node/default
    steps:
      - checkout 
      - newman/newman-run:
          collection: ./EdWings.postman_collection.json
          environment: ./EdWingsEnvironment.postman_environment.json
